### ISSUE TITLE
perl conda package is not relocatable

### ISSUE THREAD

**Issue by ericdill** [conda-forge/perl-feedstock#4]
The perl conda package is not outputting relocatable binaries. 

It seems like there are these wonky paths with triple dots in conda packaged perl that is shipped from the `conda-forge` and `dan_blanchard` channels.  That seems like a problem with the relocation since I don't think that unix paths can have these triple dots in them.  At least I was unsuccessful in finding any information about triple dots (`...`) in unix paths via google.

To see the files that have these triple-dot-paths:

``` bash
conda create -p /tmp/foo perl -c conda-forge --yes
cd /tmp/foo
grep -r "\.\.\.\/"
```

[link to the output of the above command](https://gist.github.com/ericdill/e2eba39cc6b29b74d087fb3e3d372cba) since it is sort of long

There is [this thread](http://www.london.pm/pipermail/london.pm/Week-of-Mon-20080721/014636.html) from 2008 that suggests that the combination of `-de`, `-Dprefix` and `Duserelocatableinc` has a very specific order that it needs to go in for the call to `Configure`. Specifically that `-de` needs to come last or things go wonky.  I did try that to no avail.

I discovered this while trying to build epics-base in conda-forge/staged-recipes#640 since it needs to be able to see those files.  I am basically dropping this off and running away since I've got little experience with this. Sorry!

attn @jakirkham @msarahan

**Comment by jakirkham** [comment]
Do you know a simple test for this, @ericdill? Preferably something that doesn't involve grepping.

**Comment by ericdill** [comment]
@jakirkham I do not have any idea how to test this

**Comment by jakirkham** [comment]
This might be fixed by PR ( https://github.com/conda-forge/perl-feedstock/pull/6 ). Not sure. Going to mark it as fixed at least. If it is not actually fixed by it, we can retry with a new PR.
