### ISSUE TITLE
libcrypt.so.1 is no longer available from some distributions

### ISSUE THREAD

**Issue by chrisburr** [conda-forge/perl-feedstock#56]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When using `perl` from conda-forge on Arch Linux I see:
```
perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

To reproduce with docker (I'm using micromamba for convenience but I see the same with conda/mamba on a full desktop installation of Arch):

```bash
$ docker run -it --rm archlinux:latest bash
$ pacman -Syy && pacman --noconfirm -S wget && wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba && bin/micromamba --root-prefix /micromamba-root create --name test -c conda-forge perl --yes
$ /micromamba-root/envs/test/bin/perl
```

### Installed packages

```shell
List of packages in environment: "/micromamba-root/envs/test"

  Name           Version  Build             Channel
─────────────────────────────────────────────────────────
  _libgcc_mutex  0.1      conda_forge       conda-forge
  _openmp_mutex  4.5      1_gnu             conda-forge
  libgcc-ng      11.2.0   h1d223b6_14       conda-forge
  libgomp        11.2.0   h1d223b6_14       conda-forge
  libnsl         2.0.0    h7f98852_0        conda-forge
  perl           5.32.1   2_h7f98852_perl5  conda-forge
```

### Environment info

```shell
environment : None (not found)
           env location : -
      user config files : /root/.mambarc
 populated config files :
       libmamba version : 0.22.0
     micromamba version : 0.22.0
           curl version : libcurl/7.81.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.5
       virtual packages : __unix=0=0
                          __linux=5.16.11=0
                          __glibc=2.35=0
                          __archspec=1=x86_64
               channels :
       base environment : /root/micromamba
               platform : linux-64
```

**Comment by chrisburr** [comment]
Some more information:
* `libcrypt.so.1` in conda-forge's various `sysroot_linux-*` packages so we assume it's alwasy availble
* [glibc has deprecated this library and no longer build it by default](https://sourceware.org/legacy-ml/libc-alpha/2017-08/msg01257.html)
* `manylinux` removed this from their whitelist a while ago (https://github.com/pypa/manylinux/issues/305)
* Fedora has lots of helpful information [here](https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt) about using [`libxcrypt`](https://github.com/besser82/libxcrypt) to provide `libcrypt.so.1`

I haven't done that much research but it seems like maybe we should be using `libxcrypt` instead.

@conda-forge/core Any thoughts?

**Comment by isuruf** [comment]
We can provide `libcrypto.so.2` as part of `libxcrypt` package and use it in perl, python etc and then delete the headers and `libcrypt.so.1` from the sysroot. This is what we did for `libnsl.so.1` being removed from glibc.

**Comment by chrisburr** [comment]
That makes sense to me. I've opened a PR to staged-recipes for `libxcrypt`/`libxcrypt-1`: https://github.com/conda-forge/staged-recipes/pull/18377

After it's merged I'll look at making a repodata patch to make `perl` depend on `libxcrypt-1` (and any other packages that depend on `libcrypt.so.1`).

**Comment by Bai-Chiang** [comment]
For anyone looking for solution, you need to install `libxcrypt1` package.


> After it's merged I'll look at making a repodata patch to make `perl` depend on `libxcrypt-1` (and any other packages that depend on `libcrypt.so.1`).

Maybe `libxcrypt-1` get renamed to `libxcrypt1`?

**Comment by mbargull** [comment]
Finally, done via gh-64.
