### ISSUE TITLE
Older perl versions?

### ISSUE THREAD

**Issue by bgruening** [conda-forge/perl-feedstock#9]
We want to remove the bioconda perl version once and for all. Unfortunately, we have pinned our packages against 5.22.0. What is the preferred way to get an older version of perl into conda-forge?

**Comment by ocefpaf** [comment]
Ideally in a maintenance branch. Let me know if you have rights here to create the branch or if you need me to create one for you.

**Comment by bgruening** [comment]
@ocefpaf I don't have right, would be great if you can create one? I create then a PR against this branch?

Thanks!

**Comment by ocefpaf** [comment]
>  I create then a PR against this branch?

Yep. You can send it to https://github.com/conda-forge/perl-feedstock/tree/legacy that I just created.

Thanks for maintaining it!
